import andyTourinImg from 'figma:asset/8b1779d1342c5f1af7d7addedc31e6c0ffe1463a.png';
import rondaPlamondonImg from 'figma:asset/98dafecf0b80791aff38bddfaa5c8f322ba6b9c0.png';
import lisaQuiliciImg from 'figma:asset/ccbfd8d43e94173b636dc8e9a7ded471ff410d83.png';
import lorynBlairImg from 'figma:asset/0169483f6b5320d4d3bd41b0cbb2cfc90cd31491.png';
import ronSchofieldImg from 'figma:asset/b2c0d80c877ba0c0f95b76c630f93cd584b6cff4.png';
import moniquemassetImg from 'figma:asset/24372a55b415a022fa39d25743e6545ad8e8e59e.png';
import kristiFrancoImg from 'figma:asset/3043c70253db663ec94aa1f5c4694844a0350e4e.png';
import christopherKeenanImg from 'figma:asset/c1bc8c6ed52a28c73bcb32282d240927597cae56.png';
import melissaEstesImg from 'figma:asset/05e17c06654b198b45948ae47c8faf6b1b72d8c7.png';
import shonPlamondonImg from 'figma:asset/3498777836fff416077849ad4acec9c4e27659ba.png';
import rachelQuiliciImg from 'figma:asset/06acea423ae189b48d108a0644b708017a40d34d.png';
import gerritSchmidtImg from 'figma:asset/04adbebf9b1d0b82023a354d029977f547d7a64e.png';
import suzanneSilvermanImg from 'figma:asset/d92ce3179eebaef1858338f82a04b8e604bb8abc.png';
import cherylDoughertyImg from 'figma:asset/6994f7d54ba17e1e7df23d64a8196b174d66c9c2.png';
import placeholderSilhouette from 'figma:asset/0e872a70eb168a66040ab776bb2742a307ebd76a.png';
import lauraVoorheesImg from 'figma:asset/2ebb3c364d3f9113cdf39b9df8d692dcc75ebd04.png';
import lynneScottImg from 'figma:asset/640da57585a9217b1cdffe9dd10f1b1210562fa9.png';
import susieNicholsImg from 'figma:asset/ac51669b3de395825b10f7efd47714405e19c13c.png';
import jenniferLivermoreImg from 'figma:asset/a7cee38fe867c9babf4946206824f61292cd8c8e.png';
import rachelleLungerImg from 'figma:asset/ed6dc68f11dcaf39b3bfa50ee7ba5c1621318458.png';
import shelbyMaganaImg from 'figma:asset/ac18a9a1c32b0c9e3e83ad90a82c6637edd630bd.png';
import sherryAckermanImg from 'figma:asset/d030dbbf9c11c2a8ed3ee9ff723960a9d47be36b.png';
import denaReedImg from 'figma:asset/580daefb142d81dbb7cbcf336f7194ad6eb05ef7.png';
import jenniferSammonsImg from 'figma:asset/464ba07644b6df7ab6e9999961a869320314643f.png';
import loganOrtizImg from 'figma:asset/eac356570dc32d8eb89542ac2025fad7bdca21c0.png';
import lisaMarvitzImg from 'figma:asset/423120b80437a9790b7a1fef9ac180c1d0d12ea3.png';
import amandaChanImg from 'figma:asset/f37a77664a36aab07551d8fd6c0723a9805d84e4.png';
import deniseClarkImg from 'figma:asset/8bbe45c072371c1e1d2b71348c38ab09577904d3.png';
import ginaDoyleImg from 'figma:asset/632a00ec23f36d1751658d4e8f7bdd344f45a7ac.png';
import cynthiaFailorImg from 'figma:asset/e2b243029f094563dcc1b9eb8b76027e4b3f8ff4.png';
import ryanLitteralImg from 'figma:asset/41a8c3a63cee20df0ef438b481cb8a8597d7358a.png';
import ottoAguirreImg from 'figma:asset/6e37b47fedc81e60e562f0ab8b3e86f0614a94de.png';

export interface TeamMember {
  name: string;
  title: string;
  initials: string;
  officePhone: string;
  cell: string;
  fax: string;
  email: string;
  image: any;
}

export interface Office {
  officeName: string;
  slug: string;
  officeAddress: string;
  members: TeamMember[];
}

export const officeTeams: Office[] = [
  {
    officeName: 'Reno Office',
    slug: 'reno-office',
    officeAddress: '1450 Ridgeview Drive, #100, Reno, NV 89519',
    members: [
      // Management
      {
        name: 'John Doe',
        title: 'Profit Center Manager',
        initials: 'JD',
        officePhone: '(775) 000-0000',
        cell: '(775) 000-0000',
        fax: '((775) 000-0000',
        email: '[email protected]',
        image: johnDoeImg,
      },
      {
        name: 'Ronda Plamondon',
        title: 'Chief Operating Officer / Escrow Manager',
        initials: 'RP',
        officePhone: '(775) 689-8510',
        cell: '',
        fax: '(775) 689-8520',
        email: '[email protected]',
        image: rondaPlamondonImg,
      },
      {
        name: 'Lisa Quilici',
        title: 'Chief Title Officer',
        initials: 'LQ',
        officePhone: '(775) 689-8510',
        cell: '',
        fax: '(775) 689-8520',
        email: '[email protected]',
        image: lisaQuiliciImg,
      },
      {
        name: 'Loryn Blair',
        title: 'Regional Sales Manager',
        initials: 'LB',
        officePhone: '(775) 689-8510',
        cell: '',
        fax: '(775) 689-8520',
        email: '[email protected]',
        image: lorynBlairImg,
      },
      {
        name: 'Ryan Litteral',
        title: 'Creative Director',
        initials: 'RL',
        officePhone: '(775) 689-8510',
        cell: '',
        fax: '(775) 689-8520',
        email: '[email protected]',
        image: ryanLitteralImg,
      },
      // Escrow Officers
      {
        name: 'Andrea Logan',
        title: 'Escrow Officer',
        initials: 'AL',
        officePhone: '(775) 689-8510',
        cell: '',
        fax: '(775) 689-8520',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
      {
        name: 'Carri Newham',
        title: 'Escrow Officer/ Floater',
        initials: 'CN',
        officePhone: '(775) 689-8510',
        cell: '',
        fax: '(775) 689-8520',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
      {
        name: 'Jaime Eidson-Wood',
        title: 'Escrow Officer',
        initials: 'JE',
        officePhone: '(775) 689-8510',
        cell: '',
        fax: '(775) 689-8520',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
      {
        name: 'Kristi Franco',
        title: 'Escrow Officer',
        initials: 'KF',
        officePhone: '(775) 689-8510',
        cell: '',
        fax: '(775) 800-5700',
        email: '[email protected]',
        image: kristiFrancoImg,
      },
      {
        name: 'Monique Masset',
        title: 'Escrow Officer',
        initials: 'MM',
        officePhone: '(775) 689-8510',
        cell: '',
        fax: '(775) 372-9179',
        email: '[email protected]',
        image: moniquemassetImg,
      },
      {
        name: 'Rachel Quilici',
        title: 'Junior Escrow Officer',
        initials: 'RQ',
        officePhone: '(775) 689-8510',
        cell: '(775) 737-5103',
        fax: '(775) 229-4356',
        email: '[email protected]',
        image: rachelQuiliciImg,
      },
      {
        name: 'Suzanne Silverman',
        title: 'Escrow Officer',
        initials: 'SS',
        officePhone: '(775) 689-8510',
        cell: '',
        fax: '(775) 689-8520',
        email: '[email protected]',
        image: suzanneSilvermanImg,
      },
      // Escrow Assistants
      {
        name: 'Andria Wiltshire',
        title: 'Escrow Assistant',
        initials: 'AW',
        officePhone: '(775) 689-8510',
        cell: '',
        fax: '(775) 689-8520',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
      {
        name: 'Brittany McKibben',
        title: 'Escrow Support/ Floater',
        initials: 'BM',
        officePhone: '(775) 689-8510',
        cell: '',
        fax: '(775) 689-8520',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
      {
        name: 'Dianne Granata',
        title: 'Escrow Support',
        initials: 'DG',
        officePhone: '(775) 689-8510',
        cell: '',
        fax: '(775) 689-8520',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
      {
        name: 'Melissa Estes',
        title: 'Escrow Assistant',
        initials: 'ME',
        officePhone: '(775) 689-8510',
        cell: '',
        fax: '(775) 689-8520',
        email: '[email protected]',
        image: melissaEstesImg,
      },
      // Sales
      {
        name: 'Christopher (CJ) Keenan',
        title: 'Commercial Account Executive',
        initials: 'CK',
        officePhone: '(775) 689-8510',
        cell: '',
        fax: '(775) 689-8520',
        email: '[email protected]',
        image: christopherKeenanImg,
      },
      {
        name: 'Ronnie Schofield',
        title: 'Account Executive',
        initials: 'RS',
        officePhone: '(775) 689-8510',
        cell: '(775) 870-2295',
        fax: '(775) 689-8520',
        email: '[email protected]',
        image: ronSchofieldImg,
      },
      {
        name: 'Shon Plamondon',
        title: 'Account Executive Fernley',
        initials: 'SP',
        officePhone: '(775) 689-8510',
        cell: '(775) 622-5659',
        fax: '(775) 689-8520',
        email: '[email protected]',
        image: shonPlamondonImg,
      },
      {
        name: 'Gerrit Schmidt',
        title: 'Title Assistant/ Customer Relations',
        initials: 'GS',
        officePhone: '(775) 689-8510',
        cell: '',
        fax: '(775) 689-8520',
        email: '[email protected]',
        image: gerritSchmidtImg,
      },
      // Title
      {
        name: 'Anne Ambrose',
        title: 'Title Officer',
        initials: 'AA',
        officePhone: '(775) 689-8510',
        cell: '',
        fax: '(775) 689-8520',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
      {
        name: 'Diana Beeson',
        title: 'Title Officer',
        initials: 'DB',
        officePhone: '(775) 689-8510',
        cell: '',
        fax: '(775) 689-8520',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
      {
        name: 'Jake Gerhard',
        title: 'Title Officer',
        initials: 'JG',
        officePhone: '(775) 689-8510',
        cell: '',
        fax: '(775) 689-8520',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
      {
        name: 'Julie Moreno',
        title: 'Title Officer',
        initials: 'JM',
        officePhone: '(775) 689-8510',
        cell: '',
        fax: '(775) 689-8520',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
      {
        name: 'Trish Reviglio',
        title: 'Title Officer',
        initials: 'TR',
        officePhone: '(775) 689-8510',
        cell: '',
        fax: '(775) 689-8520',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
      {
        name: 'Arlene Alvarado',
        title: 'Title Assistant',
        initials: 'AA',
        officePhone: '(775) 689-8510',
        cell: '',
        fax: '(775) 689-8520',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
      {
        name: 'Cathy Mahaffey',
        title: 'Title Assistant',
        initials: 'CM',
        officePhone: '(775) 689-8510',
        cell: '',
        fax: '(775) 689-8520',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
      {
        name: 'Chonnie Echeita',
        title: 'Title Assistant',
        initials: 'CE',
        officePhone: '(775) 689-8510',
        cell: '',
        fax: '(775) 689-8520',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
      {
        name: 'Gerrit Schmidt',
        title: 'Title Assistant/ Customer Relations',
        initials: 'GS',
        officePhone: '(775) 689-8510',
        cell: '',
        fax: '(775) 689-8520',
        email: '[email protected]',
        image: gerritSchmidtImg,
      },
      {
        name: 'Otto Aguirre',
        title: 'Title Assistant',
        initials: 'OA',
        officePhone: '(775) 689-8510',
        cell: '',
        fax: '(775) 689-8520',
        email: '[email protected]',
        image: ottoAguirreImg,
      },
      {
        name: 'Pam Globle',
        title: 'Typist',
        initials: 'PG',
        officePhone: '(775) 689-8510',
        cell: '',
        fax: '(775) 689-8520',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
    ],
  },
  {
    officeName: 'Plaza Office',
    slug: 'plaza-office',
    officeAddress: '3700 Lakeside Drive, Suite 110, Reno, NV 89509',
    members: [
      {
        name: 'Cheryl Dougherty',
        title: 'Vice President / Escrow Officer',
        initials: 'CD',
        officePhone: '(775) 689-1810',
        cell: '(775) 750-3223',
        fax: '(775) 800-5701',
        email: '[email protected]',
        image: cherylDoughertyImg,
      },
      {
        name: 'Katlin Sprague',
        title: 'Jr. Escrow Officer',
        initials: 'KS',
        officePhone: '(775) 689-1810',
        cell: '',
        fax: '(775) 800-5701',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
      {
        name: 'Laura Voorhees',
        title: 'Escrow Assistant',
        initials: 'LV',
        officePhone: '(775) 689-1810',
        cell: '',
        fax: '(775) 800-5701',
        email: '[email protected]',
        image: lauraVoorheesImg,
      },
      {
        name: 'Brie Jones',
        title: 'First Impression / Escrow Assistant',
        initials: 'BJ',
        officePhone: '(775) 689-1810',
        cell: '',
        fax: '(775) 800-5701',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
      {
        name: 'Deana Chambers',
        title: 'Escrow Assistant',
        initials: 'DC',
        officePhone: '(775) 689-1810',
        cell: '',
        fax: '(775) 800-5701',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
      {
        name: 'Jolene Hussey-Grune',
        title: 'Escrow Assistant',
        initials: 'JH',
        officePhone: '(775) 689-1810',
        cell: '',
        fax: '(775) 800-5701',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
    ],
  },
  {
    officeName: 'Damonte Office',
    slug: 'damonte-office',
    officeAddress: '500 Damonte Ranch Pkwy, Suite 820, Reno, NV 89521',
    members: [
      {
        name: 'Lynne Scott',
        title: 'Senior Escrow Officer',
        initials: 'LS',
        officePhone: '(775) 737-5090',
        cell: '(775) 412-3552',
        fax: '(775) 571-1441',
        email: '[email protected]',
        image: lynneScottImg,
      },
      {
        name: 'Susie Nichols',
        title: 'Jr. Escrow Officer',
        initials: 'SN',
        officePhone: '(775) 737-5090',
        cell: '',
        fax: '(775) 571-1441',
        email: '[email protected]',
        image: susieNicholsImg,
      },
      {
        name: 'Jennifer Livermore',
        title: 'Jr. Escrow Officer',
        initials: 'JL',
        officePhone: '(775) 737-5090',
        cell: '',
        fax: '(775) 571-1441',
        email: '[email protected]',
        image: jenniferLivermoreImg,
      },
      {
        name: 'Sandi Overlease',
        title: 'Escrow Officer / Support',
        initials: 'SO',
        officePhone: '(775) 737-5090',
        cell: '',
        fax: '(775) 571-1441',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
      {
        name: 'Jules Dionisio',
        title: 'Escrow Assistant',
        initials: 'JD',
        officePhone: '(775) 737-5090',
        cell: '',
        fax: '(775) 571-1441',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
      {
        name: 'Kaeli McCord',
        title: 'First Impression / Escrow Support',
        initials: 'KM',
        officePhone: '(775) 737-5090',
        cell: '',
        fax: '(775) 571-1441',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
      {
        name: 'Misty Corson',
        title: 'Open Orders / Escrow Support',
        initials: 'MC',
        officePhone: '(775) 737-5090',
        cell: '',
        fax: '(775) 571-1441',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
    ],
  },
  {
    officeName: 'Fernley Office',
    slug: 'fernley-office',
    officeAddress: '1032 Inglewood Dr., #100, Fernley, NV 89408',
    members: [
      {
        name: 'Rachelle Lunger',
        title: 'Escrow Officer / Title Officer',
        initials: 'RL',
        officePhone: '(775) 575-5065',
        cell: '',
        fax: '',
        email: '[email protected]',
        image: rachelleLungerImg,
      },
      {
        name: 'Steve Lunger',
        title: 'Escrow Support',
        initials: 'SL',
        officePhone: '(775) 575-5065',
        cell: '',
        fax: '',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
      {
        name: 'Cydney Vincent',
        title: 'Escrow Support',
        initials: 'CV',
        officePhone: '(775) 575-5065',
        cell: '',
        fax: '',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
      {
        name: 'Heidi Froid',
        title: 'Escrow Support',
        initials: 'HF',
        officePhone: '(775) 575-5065',
        cell: '',
        fax: '',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
      {
        name: 'Shelby Magana',
        title: 'Escrow Support',
        initials: 'SM',
        officePhone: '(775) 575-5065',
        cell: '',
        fax: '',
        email: '[email protected]',
        image: shelbyMaganaImg,
      },
    ],
  },
  {
    officeName: 'Gardnerville / Minden Office',
    slug: 'gardnerville-minden-office',
    officeAddress: '1352 U.S. Hwy 395 N, Suite 114, Gardnerville, NV 89410',
    members: [
      {
        name: 'Sherry Ackerman',
        title: 'Escrow Officer',
        initials: 'SA',
        officePhone: '(775) 737-5110',
        cell: '',
        fax: '(775) 737-5109',
        email: '[email protected]',
        image: sherryAckermanImg,
      },
      {
        name: 'Brittany Oswald',
        title: 'Escrow Support',
        initials: 'BO',
        officePhone: '(775) 737-5110',
        cell: '',
        fax: '(775) 737-5109',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
      {
        name: 'Anesa Taylor',
        title: 'Escrow Support',
        initials: 'AT',
        officePhone: '(775) 737-5110',
        cell: '',
        fax: '(775) 737-5109',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
    ],
  },
  {
    officeName: 'Sparks Office',
    slug: 'sparks-office',
    officeAddress: '4870 Vista Boulevard, #110, Sparks, NV 89436',
    members: [
      {
        name: 'Jennifer Sammons',
        title: 'Escrow Officer',
        initials: 'JS',
        officePhone: '(775) 689-8551',
        cell: '',
        fax: '(775) 507-3998',
        email: '[email protected]',
        image: jenniferSammonsImg,
      },
      {
        name: 'Logan Ortiz',
        title: 'Escrow Assistant',
        initials: 'LO',
        officePhone: '(775) 689-8551',
        cell: '',
        fax: '(775) 507-3998',
        email: '[email protected]',
        image: loganOrtizImg,
      },
      {
        name: 'Lisa Marvitz',
        title: 'Escrow Assistant',
        initials: 'LM',
        officePhone: '(775) 689-8551',
        cell: '',
        fax: '(775) 507-3998',
        email: '[email protected]',
        image: lisaMarvitzImg,
      },
      {
        name: 'Amanda Chan',
        title: 'First Impression / Escrow Support',
        initials: 'AC',
        officePhone: '(775) 689-8551',
        cell: '',
        fax: '(775) 507-3998',
        email: '[email protected]',
        image: amandaChanImg,
      },
    ],
  },
  {
    officeName: 'Zephyr Cove Office',
    slug: 'zephyr-cove-office',
    officeAddress: '212 Elks Point Road, Suite 441, Zephyr Cove, NV 89448',
    members: [
      {
        name: 'Dena Reed',
        title: 'Escrow Officer',
        initials: 'DR',
        officePhone: '(775) 841-6580',
        cell: '(775) 750-0988',
        fax: '(775) 507-3995',
        email: '[email protected]',
        image: denaReedImg,
      },
      {
        name: 'Jenn Yancey',
        title: 'Escrow Assistant',
        initials: 'JY',
        officePhone: '(775) 841-6580',
        cell: '',
        fax: '(775) 507-3995',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
    ],
  },
  {
    officeName: 'Carson City Office',
    slug: 'carson-city-office',
    officeAddress: '896 W. Nye Lane, Suite 104, Carson City, NV 89703',
    members: [
      // Escrow Officers
      {
        name: 'Denise Clark',
        title: 'Escrow Officer',
        initials: 'DC',
        officePhone: '(775) 841-6580',
        cell: '',
        fax: '(775) 507-3995',
        email: '[email protected]',
        image: deniseClarkImg,
      },
      {
        name: 'Gina Doyle',
        title: 'Escrow Officer',
        initials: 'GD',
        officePhone: '(775) 841-6580',
        cell: '',
        fax: '(775) 507-3995',
        email: '[email protected]',
        image: ginaDoyleImg,
      },
      // Sales
      {
        name: 'Cynthia Failor',
        title: 'Account Executive',
        initials: 'CF',
        officePhone: '(775) 841-6580',
        cell: '',
        fax: '(775) 507-3995',
        email: '[email protected]',
        image: cynthiaFailorImg,
      },
      // Title
      {
        name: 'Tammy Pruzzo',
        title: 'Title Officer',
        initials: 'TP',
        officePhone: '(775) 841-6580',
        cell: '',
        fax: '(775) 507-3995',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
      {
        name: 'Makina Pruzzo',
        title: 'Title Officer',
        initials: 'MP',
        officePhone: '(775) 841-6580',
        cell: '',
        fax: '(775) 507-3995',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
      {
        name: 'John Capner',
        title: 'Title Officer',
        initials: 'JC',
        officePhone: '(775) 841-6580',
        cell: '',
        fax: '(775) 507-3995',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
      {
        name: 'Haley Walker',
        title: 'Title Assistant',
        initials: 'HW',
        officePhone: '(775) 841-6580',
        cell: '',
        fax: '(775) 507-3995',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
      {
        name: 'Estela Montalvo',
        title: 'Title Assistant',
        initials: 'EM',
        officePhone: '(775) 841-6580',
        cell: '',
        fax: '(775) 507-3995',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
      {
        name: 'Donna Stewart',
        title: 'Title Assistant',
        initials: 'DS',
        officePhone: '(775) 841-6580',
        cell: '',
        fax: '(775) 507-3995',
        email: '[email protected]',
        image: placeholderSilhouette,
      },
    ],
  },
];
